### ISSUE TITLE
2. Beispielsatz nicht korrekt?

### ISSUE THREAD

**Issue by jobenaus** [Gender-i/Gender-i#3]
Bei dem Beispielsatz: "Ei Schüli gibt is Turnbeutel dis Lehri." ist Lehri meines achtens im Dativ. Müsste es dann nicht "Lehris" heißen?

**Comment by ChaosCoder** [comment]
Ist gefixt: https://github.com/Gender-i/Gender-i/commit/168c069c859bbfc04944e4c65d5964ac78ee8767
