### ISSUE TITLE
Adjektive mit bestimmtem Artikel

### ISSUE THREAD

**Issue by jobenaus** [Gender-i/Gender-i#4]
Ich fände es intuitiv bei Adjektiven grundsätzlich die i-Form zu nutzen, anstatt zwischen adjektiven mit bestimmtem und unbestimmtem Artikel zu unterscheiden. Mir fällt auf, dass ich dann immer erst überlegen muss.

**Comment by ChaosCoder** [comment]
Ja, da hast du Recht. Werde ich ändern.

**Comment by ChaosCoder** [comment]
Ist gefixt mit Commit https://github.com/Gender-i/Gender-i/commit/168c069c859bbfc04944e4c65d5964ac78ee8767
